# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types:
     - deploy-command

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: echo '::set-output name=value::${{ github.event.client_payload.slash_command.environment }}'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
